= BPMS-OCP

== ocp-credit-service

. provision
+
-----
oc new-app jboss-eap70-openshift~https://github.com/jbride/BPMS-OCP/ \
--context-dir=ocp-credit-service \
--name=cs-service
-----

. route
+
-----
oc expose service cs-service
-----

. Determine route to WSDL of `cs-service`
+
-----
echo -en "\n`oc get route cs-service --template "http://{{.spec.host}}/creditservice/CreditService?wsdl"`\n\n"
-----
+
NOTE: Point your browser to this URL to view the WSDL.

. Determine FQDN of exposed `cs-service` route
+
-----
echo -en "\n`oc get route cs-service --template "{{.spec.host}}"`\n\n"
-----
+
NOTE: The host name of the `cs-service` will be used later in this lab as the value of the following environment variable: `CREDIT_SERVICE_FQDN` 


== ocp-mortgage-rules

. provision
+
-----
oc new-app jboss-processserver63-openshift~https://github.com/jbride/BPMS-OCP \
--context-dir=ocp-mortgage-rules \
--name=mortgage-rule \
-e CREDIT_SERVICE_FQDN=`oc get route cs-service --template "{{.spec.host}}"`
-----

. route
+
-----
oc expose service mortgage-rule
-----

. Point your browser to the value of the following to view the Swagger documentation of the `Decision Server` API:
+
-----
echo -en "\n`oc get route mortgage-rule --template "http://{{.spec.host}}/kie-server/docs"`\n\n"
-----

. Point your browser to the value of the following to view the status of `kie-containers` deployed in your `Decision Server`:
+
-----
echo -en "\n`oc get route mortgage-rule --template "http://{{.spec.host}}/kie-server/services/rest/server"`\n\n"
-----

.. Authenticate using the following credentials:   kieserver / kieserver1!

== ocp-mortgage-dashboard

. provision
+
-----
oc new-app jboss-eap70-openshift~https://github.com/jbride/BPMS-OCP \
--context-dir=ocp-mortgage-dashboard \
--name=mortgage-dashboard \
-e KIE_API_REST_FQDN=`oc get route mortgage-rule --template "{{.spec.host}}"`
-----

. route
+
-----
oc expose service mortgage-dashboard
-----

. Point your browser to the value of the following to access the `mortgage` application:
+
-----
echo -en "\n`oc get route mortgage-dashboard --template "http://{{.spec.host}}/ocp-mortgage-dashboard"`\n\n"
-----


== Appendix

=== Delete OCP objects from project

The following are instructions for deletion of OCP resource per OCP `label` value:

. `cs-service` 
+
-----
oc delete all -l app=cs-service
-----

. `mortgage-rule`
+
-----
oc delete all -l app=mortgage-rule
-----

. `mortgage-dashboard`
+
-----
oc delete all -l app=mortgage-dashboard
-----

